<?php
$db = new mysqli('localhost', 'root', '', 'musicbrowser');
if (!$db) {
    die('Verbindung fehlgeschlagen\n Error: ' . mysql_error());
}

$db->set_charset("utf8");

//Künstler
$test = $db->query("INSERT INTO `kuenstler` (`pk_kuenstler`, `name`, `beschreibung`, `bild`) VALUES (
    NULL, 
    'Milky Chance', 
    'Milky Chance ist ein deutsches Folktronica-Duo, bestehend aus Clemens Rehbein und Philipp Dausch. Nachdem ihre erste, selbst produzierte Single Stolen Dance 2012 auf YouTube überraschend mehrere hunderttausend Clicks generierte, gründeten die beiden Kasseler eine eigene Plattenfirma, auf der sie am 31. Mai 2013 ihr Debütalbum Sadnecessary veröffentlichten. Mit den Singles Stolen Dance, Down by the River und Flashed Junk Mind erreichten sie unter anderem in Deutschland, Österreich, der Schweiz, Polen, Wallonien und Frankreich den ersten Platz der Singlecharts. In den Niederlanden erreichte Stolen Dance den zweiten Platz. Weitere Top-Ten-Platzierungen gab es unter anderem in Italien, Kanada, Australien und Neuseeland. 2014 wurde der US-amerikanische Markt auf das Duo aufmerksam. So zeichnete die Musikzeitschrift Spin Sadnecessary als „Album der Woche“ aus und als erste deutsche Band hatten sie einen Auftritt bei der Late-Night-Show Jimmy Kimmel Live!. Die Band gewann Preise wie den European Border Breakers Award, sowie den Echo „Bester nationaler Act im Ausland“. Nach einer Festivaltour, mit Stationen wie Coachella und Lollapalooza, veröffentlichte die Band Anfang November 2016 die Single Cocoon.', 
    'milkychance.gif')");

$test = $db->query("INSERT INTO `kuenstler` (`pk_kuenstler`, `name`, `beschreibung`, `bild`) VALUES (
    NULL, 
    'Tom Odell', 
    'Thomas Tom Peter Odell ( 24. November 1990 in Chichester) ist ein britischer Singer-Songwriter und Pianist. Mit sieben Jahren begann Tom Odell mit dem Klavierspielen, später schrieb er auch seine eigenen Songs. Mit 18 zog er von West Sussex nach Brighton, wo er am renommierten Institute of Modern Music seine musikalische Ausbildung fortsetzte. Daneben trat er auch solo auf und gründete schließlich eine Band, mit der er auch in London auftrat. Dort wurde er von Lily Allen entdeckt und für ihr eigenes Label In the Name Of verpflichtet. Er erhielt einen Plattenvertrag und nahm 2012 sein Debütalbum auf.
    Im Oktober 2012 wurde vorab eine erste EP mit dem Titel Songs from Another Love veröffentlicht. Einem Auftritt bei Later with Jools Holland folgte die Nominierung für die Talent-Awards der BBC (Sound of 2013) und MTV sowie für den Critics Choice Award der Brits, den er gewann. Die Aufmerksamkeit verhalf auch seinem Song Another Love zum Einstieg in die Top 75 der UK-Charts. In Deutschland und Österreich wurde das Lied in einer Werbekampagne der Telekom-Mobilfunksparte eingesetzt. Auch in anderen europäischen Ländern konnte sich das Lied in den Charts platzieren, unter anderem erreichte es die Top 10 in den Niederlanden. Das Debütalbum Long Way Down erschien im Juni 2013. Sein zweites Album Wrong Crowd ist am 10. Juni 2016 erschienen.', 
    'tomodell.gif')");   

$test = $db->query("INSERT INTO `kuenstler` (`pk_kuenstler`, `name`, `beschreibung`, `bild`) VALUES (
    NULL, 
    'The Rolling Stones', 
    'The Rolling Stones sind eine 1962 gegründete englische Rockband. Sie zählen zu den langlebigsten und kommerziell erfolgreichsten Gruppen in der Rockgeschichte. 1989 erfolgte die Aufnahme in die Rock and Roll Hall of Fame.  Folgt man den Ausführungen des späteren Rolling-Stones-Bassisten Bill Wyman, so hatte Brian Jones sich bei dem englischen Bandnamen The Rolling Stones (wörtlich übersetzt: „Die rollenden Steine“, sinngemäß „Die Landstreicher/Herumtreiber“) von der Zeile “I’m a rollin’ stone” im Muddy-Waters-Blues Mannish Boy aus dem Jahr 1956 inspirieren lassen. Keith Richards dagegen führt die Wahl des Namens genauso wie Dick Taylor auf das 1950 ebenfalls von Muddy Waters aufgenommene Stück Rollin’ Stone (bzw. Rollin’ Stone Blues, wie der Titel unter anderem auf britischen Schallplatten der 1950er Jahre heißt) zurück. Die in den beiden Liedern verwendete Allegorie „rolling stone“, die je nach Kontext sowohl eine positive als auch negative Konnotation haben kann, ging aus dem englischen Sprichwort “A rolling stone gathers no moss.” hervor und bezeichnet eine Person mit unstetem Lebenswandel. Zu Beginn nannte sich die Gruppe (unter Weglassung des g) noch „The Rollin’ Stones“, laut Dick Taylor aufgrund ebendieser Schreibung des Titels Rollin’ Stone Blues auf einer Schallplatte von Muddy Waters.
', 
    'rollingstones.gif')");   

$test = $db->query("INSERT INTO `kuenstler` (`pk_kuenstler`, `name`, `beschreibung`, `bild`) VALUES (
    NULL, 
    'Metallica', 
    'Metallica ist eine US-amerikanische Metal-Band. Sie wurde 1981 in Los Angeles gegründet und ist seit 1982 in San Francisco ansässig. Sie gehört zu den erfolgreichsten Metalbands der Welt und hat bislang über 110 Millionen Alben verkauft. Allein in den USA verkaufte die Band über 62 Millionen Alben und ist damit die siebterfolgreichste Künstlergruppe des Landes. Metallica wurde neunmal mit einem Grammy Award ausgezeichnet.

    Neben Slayer, Megadeth und Anthrax zählte Metallica in den 1980er Jahren zu den „großen Vier“ des Thrash Metal und gilt als die einflussreichste Metal-Band dieses Jahrzehnts. Während der 1990er-Jahre öffnete sich Metallica neuen musikalischen Einflüssen wie Bluesrock und anderen Rockstilen, womit sie ein breiteres Publikum ansprach und zugleich ihre bisherigen Fans irritierte, bevor die Band ab 2002 wieder zu ihren musikalischen Wurzeln zurückkehrte.', 
    'metallica.gif')");

$test = $db->query("INSERT INTO `kuenstler` (`pk_kuenstler`, `name`, `beschreibung`, `bild`) VALUES (
    NULL, 
    'Rag''n''Bone Man', 
    'Rory Graham (* 29. Januar 1985 in Uckfield), bekannt als Rag ’n’ Bone Man, ist ein britischer Blues- und Soul-Sänger. Aufgewachsen ist Rory Graham in East Sussex im Südosten Englands. Beide Eltern waren als Musiker aktiv,[5] ihre Vorliebe für Bluesmusik hat ihn in seiner Kindheit geprägt.[6] Seine ersten musikalischen Schritte unternahm er aber mit Hip-Hop-Musik. Im Alter von 15 Jahren war Graham unter dem Namen Rag ’n’ Bonez als Rapper in einer Drum-’n’-Bass-Crew. Nachdem er seine Rap-Fähigkeiten bei Freestyle- und Jam-Sessions in Brighton und auf UK-Tour mit Hip Hop-Künstlern wie Roots Manuva verfeinern konnte, ging er nach London zum Slipjam B im Brixtons Jamm Club. Hier gründete er mit Gizmo und DJ Direct die Crew Rum Comittee, mit der sie einige Jahre als Support act unterwegs waren und ihr eigenes Album veröffentlichten. Seinen Künstlername Rag ’n’ Bone Man, zu deutsch „Lumpensammler“, wählte er nach der britischen Comedy-Serie Steptoe and Son aus den 1960er bzw. 1970er Jahren, in denen es um zwei Altwarenhändler geht.', 
    'ragnboneman.gif')"); 

$test = $db->query("INSERT INTO `kuenstler` (`pk_kuenstler`, `name`, `beschreibung`, `bild`) VALUES (
    NULL, 
    'Annenmaykanterait', 
    'AnnenMayKantereit (auch kurz AMK) ist eine deutsche Rockband aus Köln, die 2011 gegründet wurde. Die Gruppe singt überwiegend auf Deutsch; besonderes Merkmal ist die markante, raue Stimme des Sängers Henning May. Die drei Gründungsmitglieder, aus deren Familiennamen sich der Bandname zusammensetzt, fanden sich 2011 während ihrer Schulzeit am Schiller-Gymnasium in Köln-Sülz zusammen. Anfangs noch zu dritt als Straßenmusiker in Köln unterwegs, stieß bei einer Jamsession auf der Uniwiese in Köln der Bassist Lars Lötgering dazu. 2013 erschien ihr erstes selbst aufgenommenes Album, das im Rahmen einer Release-Party im Gebäude 9 in Köln vorgestellt wurde. Das Album entstand komplett in Eigenregie und wurde teilweise auch bei Auftritten auf der Straße aufgenommen. Mittlerweile ist das Album vergriffen. Ihre Lieder veröffentlichten AnnenMayKantereit vor allem auf ihrem eigenen YouTube-Kanal. Seit August 2014 ist Malte Huck Bassist der Band.Nachdem das Video zu dem Song Wohin du gehst veröffentlicht worden war, folgte eine deutschlandweite Clubtour. Im Sommer 2014 spielte die Band auf mehreren großen Festivals, darunter das Appletree Garden Festival, das Open Flair und das Reeperbahn Festival. Im Herbst desselben Jahres spielten sie mehrere Konzerte als Vorband der Beatsteaks und begleiteten die Stadtrandlichter Tour von Clueso als Support.[10] Beim New Music Award der ARD-Jugendprogramme zählten sie 2014 zu den Finalisten.', 
    'annenmaykanterait.gif')");

$test = $db->query("INSERT INTO `kuenstler` (`pk_kuenstler`, `name`, `beschreibung`, `bild`) VALUES (
    NULL, 
    'Red Hot Chili Peppers', 
    'Red Hot Chili Peppers (Abkürzung: RHCP) ist eine kalifornische Funk- und Alternative-Rockband. Sie zählt zu den kommerziell erfolgreichsten Vertretern des Crossover. Ihr Album Blood Sugar Sex Magik gilt als eines der bedeutendsten dieses Genres. Die Geschichte der Red Hot Chili Peppers begann am 13. Februar 1983, als die Schulfreunde Anthony Kiedis (Gesang), Michael „Flea“ Balzary (Bass), Hillel Slovak (Gitarre) und Jack Irons (Schlagzeug) im „Rhythm-Lounge“-Club in Los Angeles ihren ersten gemeinsamen Auftritt feierten. Die Truppe nannte sich vorerst „Tony Flow and the Miraculously Majestic Masters of Mayhem“. Obwohl diese nur zum Spaß für einen einmaligen Auftritt gegründet wurde (Flea, Hillel Slovak und Jack Irons spielten in einer weit erfolgreicheren Band namens „What Is This“), überraschten sie mit ihrem Song Out In L.A. die Zuschauer durch ihr Zusammenspiel von Rap, Rock, Funk und Punk. Der Clubbesitzer war so beeindruckt, dass die Band für die darauf folgende Woche gebucht wurde. Bei ihrem nächsten Auftritt war der Club bereits voll, da sich Gerüchte über die neue Band in L.A. herumgesprochen hatten. Bald darauf entstand der Name Red Hot Chili Peppers, laut Kiedis Autobiographie „Scar Tissue“ (2004) eine Ableitung eines klassischen amerikanischen Blues- oder Jazz-Bandnamens, in denen oft Elemente wie „Red Hot“ oder „Chili“ aufgetaucht seien (z. B. Jelly Roll Mortons Red Hot Peppers).
Die neue Band kam rasch weit herum und veröffentlichte im August 1984 ihr Debütalbum The Red Hot Chili Peppers, welches von Andy Gill (Gang of Four) produziert wurde. Slovak und Irons hatten die Band bereits vor Beginn der Aufnahmen verlassen. Ihre alte Band „What Is This?“ (mit der sie weiterhin geprobt hatten) hatte auch einen Plattenvertrag, und sie entschieden sich dafür, in dieser Band zu bleiben. Sie wurden durch Cliff Martinez (Schlagzeug) und Jack Sherman (Gitarre) ersetzt. Mit Sherman kam es immer wieder zu Konflikten, da er einen ganz anderen Lebensstil pflegte als die anderen Bandmitglieder. Außerdem funktionierte die Zusammenarbeit mit Andy Gill nicht besonders gut, da dieser es, im Gegensatz zu den Peppers, auf einen radiokompatiblen Sound anlegte.
Nachdem Sherman aus der Band geworfen wurde, entschied sich Slovak, bei den Chili Peppers erneut als Gitarrist einzusteigen. Am Schlagzeug blieb Cliff Martinez. Das nächste Album Freaky Styley wurde mit dem Funk-Musiker George Clinton produziert. Bei den Aufnahmen zu Freaky Styley wirkten auch Maceo Parker und Fred Wesley, Bläser der Band von James Brown, mit.
Ihr nächstes Album The Uplift Mofo Party Plan war um einiges erfolgreicher als Freaky Styley. Es handelt sich dabei um das einzige Studioalbum, das in der ursprünglichen Besetzung eingespielt wurde, da Jack Irons wieder Peppers-Schlagzeuger wurde. Es wurde mit dem Produzenten Michael Beinhorn aufgenommen.Schon zu dieser Zeit waren sowohl Kiedis als auch Slovak heroinabhängig. Im Juni 1988, kurz nachdem die Band von einer Europatournee zurückgekehrt war, starb Hillel Slovak an einer Überdosis Heroin. Die restlichen drei Bandmitglieder waren schockiert. Jack Irons verließ die Red Hot Chili Peppers mit der Begründung, er wolle nicht an etwas teilnehmen, bei dem seine Freunde sterben. (Er spielte später bei der Band „Pearl Jam“, die mit den Peppers auch Gigs zusammen gespielt haben.) Anthony Kiedis war durch den Tod seines besten Freundes sehr betroffen – hatte er doch einen ähnlichen Lebensstil – und nahm sich eine kurze Auszeit. Er besuchte eine Entzugsklinik und lebte danach fünf Jahre lang drogenabstinent.', 
    'redhot.gif')");

$test = $db->query("INSERT INTO `kuenstler` (`pk_kuenstler`, `name`, `beschreibung`, `bild`) VALUES (
    NULL, 
    'The Beatles', 
    'The Beatles waren eine britische Rockband in den 1960er Jahren. Mit mehr als 600 Millionen[1] – nach Schätzungen ihrer Plattenfirma EMI sogar mehr als einer Milliarde[2] – verkauften Tonträgern sind sie die bisher kommerziell erfolgreichste Band der Musikgeschichte. Die musikalischen Ursprünge der Band liegen im Rock ’n’ Roll der ausgehenden 1950er Jahre, in den dann sehr bald Stilelemente der Liverpooler Beatmusik einflossen. Ihre erste Single Love Me Do erschien 1962. Den weltweiten Durchbruch schaffte die Gruppe im Jahr 1963 mit der Single I Want to Hold Your Hand. Aufgrund ihres damals neuartigen Musikstils und ihres öffentlichen Auftretens entwickelten sie sich schnell zu einer der populärsten Bands. Den Höhepunkt ihrer Karriere erreichten die Beatles zwischen 1964 und 1968, als sie zeitweise in fast allen Ländern die Hitparaden anführten. Im Jahr 1970 trennten sich die Wege der vier Bandmitglieder aufgrund interner Spannungen. Die Musiker verfolgten danach erfolgreich eigene Musikprojekte.', 
    'thebeatles.gif')");

$test = $db->query("INSERT INTO `kuenstler` (`pk_kuenstler`, `name`, `beschreibung`, `bild`) VALUES (
    NULL, 
    'Nirvana', 
    'Nirvana war eine US-amerikanische Grunge-Band aus Aberdeen im Bundesstaat Washington. Nachdem die Band im Jahr 1987 gegründet wurde, erreichte sie Ende 1991 mit dem Song Smells Like Teen Spirit und dem Album Nevermind große Popularität. Sieben Jahre nach der Gründung löste sich die Band im Frühjahr 1994 im Zusammenhang mit dem Tod des Sängers und Songschreibers Kurt Cobain auf. Die Band verkaufte ca. 75 Millionen Tonträger. Nirvana wurde im Jahr 1987 von Kurt Cobain und Krist Novoselić gegründet. Die beiden lernten sich 1984 in der Schule und vor allem im Umfeld der Band The Melvins kennen. Im Winter 1985 gründete Cobain zusammen mit dem späteren The-Melvins-Schlagzeuger Dale Crover als Bassist die Band Fecal Matter. Nachdem die Gruppe zwei Demos bei Cobains Tante Mari aufgenommen und einige Konzerte, unter anderem als Vorband von The Melvins, gespielt hatte, löste sie sich jedoch wieder auf. Die Fecal-Matter-Demo vom Dezember 1985 überzeugte Novoselić, mit Cobain eine Band zu gründen. Im selben Monat gründeten die beiden, Cobain als Sänger und Novoselić am Bass, zusammen mit dem Schlagzeuger Steve Newman die Creedence-Clearwater-Revival-Coverband The Sellouts. Im gleichen Monat hatten Cobain und Novoselić eine weitere Band mit dem Schlagzeuger Bob McFadden, beide Bands lösten sich jedoch noch im selben Winter auf. Im März 1986 zog Krist Novoselić mit seiner Freundin Shelli nach Phoenix in Arizona. Nachdem Novoselić im Herbst 1986 wieder zurück nach Aberdeen zog, begannen er und Cobain sofort mit der Suche nach einem neuen Schlagzeuger. Im Januar 1987 gründeten sie schließlich mit Aaron Burckhard eine Band, die unter den Namen Ted Ed Fred und The Stiff Woodies spielte. Schnell traten erste Differenzen auf – während Burckhard hauptsächlich Metal hörte, waren Novoselić und Cobain von Gang of Four, Scratch Acid und Butthole Surfers inspiriert. Darüber hinaus zeigte Burckhard deutlich weniger Engagement als die beiden. Später sagte Kurt Cobain, dessen Arbeitseifer auch Novoselić anfangs überforderte: „Ich wollte eine Platte herausbringen oder ein paar Auftritte machen und verhindern, dass das Projekt genauso den Bach hinunterging wie alle anderen in den vergangenen sechs Jahren.“ – Kurt Cobain, zitiert nach Come As You Are', 
    'nirvana.gif')");

$test = $db->query("INSERT INTO `kuenstler` (`pk_kuenstler`, `name`, `beschreibung`, `bild`) VALUES (
    NULL, 
    'Alt-J', 
    'Alt-J (Eigenschreibweise: alt-J, auch ∆) ist eine britische Alternative-Folk-Band aus Leeds. Ihr bisher größter Erfolg ist der Gewinn des englischen Mercury Music Prize 2012. Die Anfänge der Band gehen auf das Jahr 2007 zurück. Damals trafen sich Gwil Sainsbury, Joe Newman, Gus Unger-Hamilton und Thom Green an der Universität Leeds, wo Sainsbury, Newman und Green Kunst und Unger-Hamilton englische Literatur studierten. In ihrem zweiten Studienjahr spielte Newman Sainsbury ein paar seiner Lieder vor, bei denen er von seinem Gitarre spielenden Vater inspiriert wurde. Daraufhin beschlossen die beiden, eine Band zu gründen. Die ersten Aufnahmen entstanden noch in ihren Schlafräumen an der Universität. Nach Green stieß Unger-Hamilton als letzter zur Band, die in den folgenden zwei Jahren zuerst unter dem Namen Daljit Dhaliwal und später als The Films hauptsächlich in Leeds auftrat. Um Verwechslungen mit der amerikanischen Indie-Rock-Band The Films zu vermeiden, nahmen sie dann mit alt-J einen neuen Bandnamen an. Am 1. November 2012 gewann alt-J den renommierten Mercury Music Prize. Bei den BRIT Awards 2013 war die Band in drei Kategorien nominiert. Am 11. Februar 2014 verkündeten alt-J auf ihrem offiziellen Twitter-Account, dass Gwil Sainsbury die Band verlassen habe, bekräftigten aber zwei Tage später auf Facebook, dass die Band weiter an ihrem zweiten Album arbeite. Das neue Album This Is All Yours erschien am 22. September 2014, die Vorab-Single Hunger of the Pine wurde erstmals am 18. Juni im Programm der BBC gespielt.', 
    'altj.gif')");

//Album
$db->query("INSERT INTO `album` (`pk_album`, `name`, `bild`, `fk_kuenstler`) VALUES (NULL, 'Sadnecessary', 'milkychance.gif', '1')");
$db->query("INSERT INTO `album` (`pk_album`, `name`, `bild`, `fk_kuenstler`) VALUES (NULL, 'Wrong Crowd', 'tomodell.gif', '2')");
$db->query("INSERT INTO `album` (`pk_album`, `name`, `bild`, `fk_kuenstler`) VALUES (NULL, 'Blue & Lonesome', 'rollingstones.gif', '3')");
$db->query("INSERT INTO `album` (`pk_album`, `name`, `bild`, `fk_kuenstler`) VALUES (NULL, 'Hardwired... To Self-Destruct', 'metallica.gif', '4')");
$db->query("INSERT INTO `album` (`pk_album`, `name`, `bild`, `fk_kuenstler`) VALUES (NULL, 'Human', 'ragnboneman.gif', '5')");
$db->query("INSERT INTO `album` (`pk_album`, `name`, `bild`, `fk_kuenstler`) VALUES (NULL, 'Alles nix konkretes', 'annenmaykanterait.gif', '6')");
$db->query("INSERT INTO `album` (`pk_album`, `name`, `bild`, `fk_kuenstler`) VALUES (NULL, 'Stadium Arcadium', 'redhot.gif', '7')");
$db->query("INSERT INTO `album` (`pk_album`, `name`, `bild`, `fk_kuenstler`) VALUES (NULL, 'Abbey Road', 'thebeatles.gif', '8')");
$db->query("INSERT INTO `album` (`pk_album`, `name`, `bild`, `fk_kuenstler`) VALUES (NULL, 'Nevermind', 'nirvana.gif', '9')");
$db->query("INSERT INTO `album` (`pk_album`, `name`, `bild`, `fk_kuenstler`) VALUES (NULL, 'An awesome wave', 'altj.gif', '10')");

//Songs
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Stunner', '1', '1', 'milkychance.gif', '25', 'https://www.youtube.com/watch?v=HHPLi3hW0jU')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Flashed Junk Mind', '1', '1', 'milkychance.gif', '13', 'https://www.youtube.com/watch?v=r8BsuT0PWdI')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Becoming', '1', '1', 'milkychance.gif', '21', 'https://www.youtube.com/watch?v=o0DCDlRGlzM')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Wrong Crowd', '2', '2', 'tomodell.gif', '32', 'https://www.youtube.com/watch?v=uvosjKUKCLo')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Magnetised', '2', '2', 'tomodell.gif', '34', 'https://www.youtube.com/watch?v=4fgzu9Fo66Y')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Concrete', '2', '2', 'tomodell.gif', '29', 'https://www.youtube.com/watch?v=bnZxWpwvFEk')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Helpless', '4', '4', 'metallica.gif', '16', 'https://www.youtube.com/watch?v=60n2YB4MZ5U')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Hardwired', '4', '4', 'metallica.gif', '21', 'https://www.youtube.com/watch?v=zaZswCtNmEg')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('All of your love', '3', '3', 'rollingstones.gif', '19', 'https://www.youtube.com/watch?v=2ZHL8mIM-8I')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Just your fool', '3', '3', 'rollingstones.gif', '23', 'https://www.youtube.com/watch?v=wKzMxirIrFQ')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Human', '5', '5', 'ragnboneman.gif', '10', 'https://www.youtube.com/watch?v=L3wKzyIN1yk')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Pocahontas', '6', '6', 'annenmaykanterait.gif', '30', 'https://www.youtube.com/watch?v=DraA3PUuoQc')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Oft gefragt', '6', '6', 'annenmaykanterait.gif', '24', 'https://www.youtube.com/watch?v=TxZMfufRJfo')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Barfuss am Klavier', '6', '6', 'annenmaykanterait.gif', '27', 'https://www.youtube.com/watch?v=tERRFWuYG48')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Can''t stop', '7', '7', 'redhot.gif', '28', 'https://www.youtube.com/watch?v=l-E0nFErk3w')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Snow (Hey Oh)', '7', '7', 'redhot.gif', '34', 'https://www.youtube.com/watch?v=yuFI5KSPAt4')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Warlocks', '7', '7', 'redhot.gif', '20', 'https://www.youtube.com/watch?v=yjQi0ysL-go')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Something', '8', '8', 'thebeatles.gif', '19', 'https://www.youtube.com/watch?v=X5IVp25InsA')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Come Together', '8', '8', 'thebeatles.gif', '29', 'https://www.youtube.com/watch?v=tW-daYDX9XE')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Smells Like Teen Spirit', '9', '9', 'nirvana.gif', '33', 'https://www.youtube.com/watch?v=hTWKbfoikeg')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('In Bloom', '9', '9', 'nirvana.gif', '25', 'https://www.youtube.com/watch?v=6vqfuAczm7g')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Come as you are', '9', '9', 'nirvana.gif', '28', 'https://www.youtube.com/watch?v=vabnZ9-ex7o')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Brezeblocks', '10', '10', 'altj.gif', '33', 'https://www.youtube.com/watch?v=rVeMiVU77wo')");
$db->query("INSERT INTO `song` (`name`, `fk_kuenstler`, `fk_album`, `bild`, `bewertung`, `youtubeLink`) VALUES ('Handmade', '10', '10', 'altj.gif', '26', 'https://www.youtube.com/watch?v=O3fIS4EToGc')");

$db->close();
?>